default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sample_app_dev

test:
  <<: *default
  database: sample_app_test

production:
  <<: *default
  database: sample_app_prod
