# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fd59a041bfac23afc5e49eb0caa3bc4e6b7288001f0726532953767000af0487993079cfd0c783578604283cbe480341b35741982e3531776a54feb78b6affd

test:
  secret_key_base: 91cfa071b8a600e2b981c25bde5ea1502b1d144a3c8ada503a5cb790e3d25c212b980048eb10b10a13371d501f151916de8fdd9e1ddeec735f83fb2588bc4816

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
